version: '3'
services:
  directus:
    restart: always
    image: directus/directus:10.10.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    environment:
      - KEY=${KEY}
      - SECRET=${SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - WEBSOCKETS_ENABLED=${WEBSOCKETS_ENABLED}
    depends_on:
      - db

  frontend:
    build:
      context: ./full-stack-project-with-tatenda
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    restart: always
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  db_data: